# Generated by Django 4.0.2 on 2022-02-15 15:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Category_choice',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Middag'), ('2', 'Lunsj'), ('3', 'Frokost'), ('4', 'Rask'), ('5', 'kjøtt'), ('6', 'fisk'), ('7', 'kyllig'), ('8', 'vegetar')], default='1', max_length=15),
            preserve_default=False,
        ),
    ]
