# Generated by Django 4.0.2 on 2022-02-17 16:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recipe_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Category_choice',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Middag'), (2, 'Lunsj'), (3, 'Frokost'), (4, 'Rask'), (5, 'Kjøtt'), (6, 'Fisk'), (7, 'Kylling'), (8, 'Vegetar')], max_length=15),
        ),
    ]
