# Generated by Django 4.0.2 on 2022-02-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_recipe_category_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instruction',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
