# Generated by Django 4.0.2 on 2022-03-02 17:53

from datetime import timedelta

from django.db import migrations
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.core.files import File
from django.contrib.auth.management import create_permissions
from django.db import transaction

users = [
  {
    "username": "Olav",
    "email": "olav@email.com",
    "password": "supersecret123",
    "is_staff": False
  },
  {
    "username": "Gunnar",
    "email": "gungun@gmail.com",
    "password": "rockyou5",
    "is_staff": True
  },
  {
    "username": "Frida",
    "email": "fri.da@stud.ntnu.no",
    "password": "ilovekanelboller",
    "is_staff": False
  },
  {
    "username": "h7x4",
    "email": "h7x4@stud.ntnu.no",
    "password": "1234",
    "is_staff": True
  },
]

categories = [
  'Middag',
  'Lunsj',
  'Frokost',
  'Rask mat',
  'Kjøtt',
  'Fisk',
  'Kylling',
  'Vegetar',
  'Indisk',
  'Kinesisk',
  'Italiensk',
  'Amerikansk',
  'Dessert',
]

recipes = [
  {
    'name': 'Spaghetti Carbonara',
    'author': 'Olav',
    'portion': 4,
    'duration': timedelta(minutes=5),
    'recipe_image': '.example_images/spaghetti_carbonara.jpg',
    'categories': [
      'Middag',
      'Rask mat',
    ],
    'ingredients': [
      {
        'name': 'Tomat',
        'amount': 3,
        'unit': 'stk'
      },
      {
        'name': 'Spaghetti',
        'amount': 500,
        'unit': 'g'
      },
    ],
    'description': """
      Discover how to make superb spaghetti carbonara. This cheesy pasta dish is an Italian favourite and with the right technique, you can make it perfect every time
    """,
    'instruction': """
      STEP 1
      Put a large saucepan of water on to boil.

      STEP 2
      Finely chop the 100g pancetta, having first removed any rind. Finely grate 50g pecorino cheese and 50g parmesan and mix them together.

      STEP 3
      Beat the 3 large eggs in a medium bowl and season with a little freshly grated black pepper. Set everything aside.

      STEP 4
      Add 1 tsp salt to the boiling water, add 350g spaghetti and when the water comes back to the boil, cook at a constant simmer, covered, for 10 minutes or until al dente (just cooked).

      STEP 5
      Squash 2 peeled plump garlic cloves with the blade of a knife, just to bruise it.

      STEP 6
      While the spaghetti is cooking, fry the pancetta with the garlic. Drop 50g unsalted butter into a large frying pan or wok and, as soon as the butter has melted, tip in the pancetta and garlic.

      STEP 7
      Leave to cook on a medium heat for about 5 minutes, stirring often, until the pancetta is golden and crisp. The garlic has now imparted its flavour, so take it out with a slotted spoon and discard.

      STEP 8
      Keep the heat under the pancetta on low. When the pasta is ready, lift it from the water with a pasta fork or tongs and put it in the frying pan with the pancetta. Don’t worry if a little water drops in the pan as well (you want this to happen) and don’t throw the pasta water away yet.

      STEP 9
      Mix most of the cheese in with the eggs, keeping a small handful back for sprinkling over later.

      STEP 10
      Take the pan of spaghetti and pancetta off the heat. Now quickly pour in the eggs and cheese. Using the tongs or a long fork, lift up the spaghetti so it mixes easily with the egg mixture, which thickens but doesn’t scramble, and everything is coated.

      STEP 11
      Add extra pasta cooking water to keep it saucy (several tablespoons should do it). You don’t want it wet, just moist. Season with a little salt, if needed.

      STEP 12
      Use a long-pronged fork to twist the pasta on to the serving plate or bowl. Serve immediately with a little sprinkling of the remaining cheese and a grating of black pepper. If the dish does get a little dry before serving, splash in some more hot pasta water and the glossy sauciness will be revived.
    """,
  },
  {
    'name': 'Kanelboller',
    'author': 'Frida',
    'portion': 3,
    'duration': timedelta(minutes=30),
    'recipe_image': '.example_images/cinnamon_rolls.jpg',
    'categories': [
      'Dessert',
      'Lunsj',
    ],
    'ingredients': [
      {
        'name': 'Kanel',
        'amount': 3,
        'unit': 'ts'
      },
      {
        'name': 'Hvetemel',
        'amount': 1,
        'unit': 'kg'
      },
      {
        'name': 'Sukker',
        'amount': 10,
        'unit': 'kg'
      },
    ],
    'description': 'MMmmmmmmhhh, I ❤️ kanelbolleonsdag',
    'instruction': """
1. Kutt smør i terninger, og la det temperere seg litt mens deigen elter.
2. Ha hvetemel, sukker, gjær, salt og kardemomme i en bakebolle til kjøkkenmaskin. Bruker du fersk gjær kan du smuldre gjæren i bollen, eller røre den ut i melken. Alt vil ettehvert blande seg godt, så begge deler er like bra.
3. Ha i egg, og spe med melk (kald eller romtemperert). Hold tilbake 1/2 dl, tilsett mer melk etter hvert hvis deigen virker for fast.
4. Sett en deigkrok i kjøkkenmaskinen og elt deigen i ca. 15 minutter. 
5. Tilsett smøret og elt deigen videre i ca. 10 minutter, til deigen er myk og elastisk. Ta gjerne "glutentesten" mot slutten av eltingen. Strekk en liten deigklump mellom fingrene og forsøk å få en tynn, gjennomsiktig hinne. Er deigen elastisk og smidig er den klar for heving, er den "kort" og revner - elt litt til.
6. Dekk til deigen og la heve i ca. 1 time, eller til dobbel størrelse. 
7. Mens deigen hever kan du lage fyllet: Bland romtemperert smør med sukker og kanel.
8. Ha deigen på et melet bakebord. Kjevle den ut en til 1 cm. tykk rektangelformet leiv og smør på fyllet. Brett deigen i to på langs og skjær ut remser på 2 cm på langs. Tvinn hver remse og snurr dem to ganger rundt to samlede fingre. Avslutt med å trekke siste del av remsen på tvers over deigsirkelen og fest enden på undersiden. 
9. Sett kanelknutene på stekeplate med bakepapir og dekk til, og la dem etterheve minst 30 minutter. 
10. Sjekk kanelknutene midt i ovnen på 200 °C i 10-15 minutter. Avkjøl på rist.
    """,
  },
  {
    'name': 'Burger',
    'author': 'Gunnar',
    'portion': 2,
    'duration': timedelta(minutes=5),
    'recipe_image': '.example_images/burger.jpg',
    'categories': [
      'Middag',
      'Rask mat',
    ],
    'ingredients': [
      {
        'name': 'Salat',
        'amount': 2,
        'unit': 'blader'
      },
      {
        'name': 'Burgerbrød',
        'amount': 2,
        'unit': 'stk'
      },
      {
        'name': 'Sylteagurk',
        'amount': 3,
        'unit': 'biter'
      },
    ],
    'description': 'God og rask middag. Passer supert før fotballtrening',
    'instruction': """
1. Ha kjøttdeig, salt, pepper og vann i en bolle og rør deigen sammen. Ikke rør for lenge, deigen skal ikke bli seig.
2. Ha litt vann på en fjøl og form deigen til runde kaker som klemmes ut til store flate burgere.
3. Stek burgere i en stekepanne med margarin eller olje. Bruk sterk varme og stek på den ene siden til det pipler ut kjøttsaft. Snu burgerne og stek videre på den andre siden til det igjen pipler ut kjøttsaft. Da er burgerne medium stekt.
4. Gjør klar tilbehøret. Varm hamburgerbrød som anvist på pakken. Vask salat. Kutt tomat, rødløk og syltet agurk i skiver.
5. Fyll brødene med salatblad, burgere, tomat, rødløk og syltet agurk. Ha gjerne på en dressing du liker godt, eller en hjemmelaget ketchup. Server gjerne med potetchips. 
    """,
  }
]

comments = [
  {
    "author": "Gunnar",
    "recipe": "Spaghetti Carbonara",
    "body": "Superdigg!",
  },
  {
    "author": "Olav",
    "recipe": "Kanelboller",
    "body": "Disse var skikkelig gode! Tusen takk!",
  },
  {
    "author": "Gunnar",
    "recipe": "Kanelboller",
    "body": "Æsj, jeg liker ikke kanel",
  },
]

def add_users(apps, schema_editor):
  SplendEatUser = apps.get_model('api', 'SplendEatUser')
  Permission = apps.get_model('auth', 'Permission')

  # https://stackoverflow.com/questions/38822273/how-to-add-a-permission-to-a-user-group-during-a-django-migration
  for app_config in apps.get_app_configs():
      app_config.models_module = True
      create_permissions(app_config, verbosity=0)
      app_config.models_module = None

  for userDict in users:
    userDict['password'] = make_password(userDict['password'])
    user = SplendEatUser.objects.create(**userDict)
    if userDict['is_staff']:
      for permission in Permission.objects.all():
        user.user_permissions.add(permission)
        user.save()

def add_categories(apps, schema_editor):
  Category = apps.get_model('api', 'Category')
  for category in categories:
    Category.objects.create(name=category)

def add_recipes(apps, schema_editor):
  Recipe = apps.get_model('api', 'Recipe')
  Ingredient = apps.get_model('api', 'Ingredient')
  SplendEatUser = apps.get_model('api', 'SplendEatUser')
  Category = apps.get_model('api', 'Category')
  with transaction.atomic():
    for recipe in recipes:
      recipe_author = SplendEatUser.objects.get(username=recipe['author'])

      r = Recipe.objects.create(
        name=recipe['name'],
        portion=recipe['portion'],
        duration=recipe['duration'],
        description=recipe['description'],
        instruction=recipe['instruction'],
        author=recipe_author,
      )

      initial_path = settings.BASE_DIR / recipe["recipe_image"]
      with open(initial_path, 'rb') as f:
        r.recipe_image.save(recipe["recipe_image"].split("/")[-1], File(f))

      for c in recipe['categories']:
        r.categories.add(Category.objects.get(name=c))

      for i in recipe['ingredients']:
        Ingredient.objects.create(recipe=r, **i)

def add_comments(apps, schema_editor):
  Recipe = apps.get_model('api', 'Recipe')
  Comment = apps.get_model('api', 'Comment')
  SplendEatUser = apps.get_model('api', 'SplendEatUser')

  with transaction.atomic():
    for comment in comments:
      comment_author = SplendEatUser.objects.get(username=comment['author'])
      comment_recipe = Recipe.objects.get(name=comment['recipe'])
      Comment.objects.create(
        author=comment_author,
        recipe=comment_recipe,
        body=comment['body']
      )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_category_remove_recipe_category_choice_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ("contenttypes", "0002_remove_content_type_name")
    ]

    operations = [
        migrations.RunPython(add_users),
        migrations.RunPython(add_categories),
        migrations.RunPython(add_recipes),
        migrations.RunPython(add_comments),
    ]
